name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Set ENV vars - gitsha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Set ENV vars - commit url
      run: echo "COMMIT_URL=`echo https://github.com/kratochj/docker-apache-php55/commit/${GITHUB_SHA}`" >> $GITHUB_ENV

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: php-5.5-apache
        tags: 1, latest, ${{ env.SHORT_SHA }}
        registry: ${{ vars.DOCKER_REGISTRY }}
        dockerfile: Dockerfile
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        enableBuildKit: true
        labels: "commit=${{ env.SHORT_SHA }}"

#    - name: Build the Docker image
#      run: docker build app --file app/Dockerfile --tag my-image-name:$(date +%s)
